apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: fraud-detection-app
    release: {{ .Release.Name }}
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app: fraud-detection-app
    release: {{ .Release.Name }}
